title: "Parallelizing Max Flow on a GPU"
description: "Our website detailing the progress of our max-flow GPU implementation project for CMU's 15-618."
theme: minima  # Uses the default GitHub Pages theme
baseurl: "/max-flow-gpu"  # Needed if using a project site (not user.github.io)
url: "https://achstar.github.io"

# Navigation (Optional)
header_pages:
  - index.md
  - proposal.md
  - milestone.md
  - final.md

# Enable Markdown & Plugins
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-seo-tag
